#NORMFLUODAT-PERFECT MVP
fpath <- system.file("extdata", "dat_2.dat", package = "normfluodbf", mustWork = TRUE)
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'hundred')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'one')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'hundred')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'one')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'hundred')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'one')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40)
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3))
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3), read_direction = 'horizontal')

#Extreme cases
fpath <- system.file("extdata", "dat_7.dat", package = "normfluodbf", mustWork = TRUE)
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'hundred')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'one')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'hundred')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'one')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'hundred')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'one')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40)
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A'), cols_used = c(1))
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A'), cols_used = c(1,2))

normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3))
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluodat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3), read_direction = 'horizontal')

#NORMFLUODATLITE-PERFECT LESS CPUINT-NO ASSIGN FUNCTION

fpath <- system.file("extdata", "dat_1.dat", package = "normfluodbf", mustWork = TRUE)
normalized_fluo_dat <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'hundred')
normalized_fluo_dat <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'one')
normalized_fluo_dat <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'hundred')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'one')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'hundred')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'one')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40)
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3))
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3), read_direction = 'horizontal')

#Extreme cases
fpath <- system.file("extdata", "dat_5.dat", package = "normfluodbf", mustWork = TRUE)
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'hundred')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'one')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'hundred')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'one')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'hundred')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'one')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40)
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3))
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3))
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3))

normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3))
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluodatlite(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3), read_direction = 'horizontal')

#NORMFLUODATFULL
fpath <- system.file("extdata", "dat_3.dat", package = "normfluodbf", mustWork = TRUE)
normalized_fluo_dat <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'hundred')
normalized_fluo_dat <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'one')
normalized_fluo_dat <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'hundred')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'one')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'hundred')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'one')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40)
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3))
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3), read_direction = 'horizontal')

fpath <- system.file("extdata", "dat_7.dat", package = "normfluodbf", mustWork = TRUE)
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'hundred')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'one')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical', norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'hundred')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'one')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal', norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'hundred')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'one')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'z-score')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'decimal')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), norm_scale = 'raw')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40)
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3))
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluodatfull(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3), read_direction = 'horizontal')

#NORMFLUORDAT
fpath <- system.file("extdata", "dat_3.dat", package = "normfluodbf", mustWork = TRUE)
normalized_fluo_dat <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40)
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3))
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 3, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3), read_direction = 'horizontal')


fpath <- system.file("extdata", "dat_5.dat", package = "normfluodbf", mustWork = TRUE)
normalized_fluo_dat <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), read_direction = 'horizontal')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'))
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40)
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3))
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3), read_direction = 'vertical')
normalized_fluo_dat_advv <- normfluordat(dat=fpath, tnp = 1, cycles = 40,rows_used = c('A','B','C'), cols_used = c(1,2,3), read_direction = 'horizontal')

